project_id = "fpbvnrxrmesxgnaxkiua"

[functions.extract-invoice]
verify_jwt = false

[functions.extract-bank-pdf]
verify_jwt = false

[functions.send-proforma-email]
verify_jwt = false

[functions.accountant-portal-access]
verify_jwt = false

[functions.manage-users]
verify_jwt = false
